### ISSUE TITLE
feat: Support of truthy/falsy

### ISSUE THREAD

**Issue by cka29** [kingwill101/liquify#10]
Would be nice to support https://shopify.github.io/liquid/basics/truthy-and-falsy/ . For more context:
It should be possible to use something like this, where `valueFromContext` is passed as dynamic value as data to the renderer. It can be `null` or an empty string for example. If `null` it should evaluate to `false`. Empty strings considered as Truthy.

```
{% assign value = valueFromContext %}
{% if value %}
True
{% endif %}
```

**Comment by kingwill101** [comment]
> Would be nice to support https://shopify.github.io/liquid/basics/truthy-and-falsy/ . For more context:
> It should be possible to use something like this, where `valueFromContext` is passed as dynamic value as data to the renderer. It can be `null` or an empty string for example. If `null` it should evaluate to `false`. Empty strings considered as Truthy.
> 
> ```
> {% assign value = valueFromContext %}
> {% if value %}
> True
> {% endif %}
> ```
> 

kinda assumed that was already supported 🤔 

Away at the moment ,so  will have a look later.
