### ISSUE TITLE
Support of Money Filter

### ISSUE THREAD

**Issue by cka29** [kingwill101/liquify#2]
Hey @kingwill101 do you know if this package will support filters like [Money](https://shopify.dev/docs/api/liquid/filters/money) for example? Input could look like this
```
"{\"amount\":\"100.0\",\"currency_code\":\"USD\"}"
```

Thanks!

**Comment by kingwill101** [comment]
We currently only support core liquid filters.

Looking at the documentation it seems to depend on Shopify specific things. Meaning  the implementation would be slightly different

**Comment by cka29** [comment]
@kingwill101 thanks for your response. So for this usecase it would be better to create a custom module that parses the json string into e.g. `$100` right?

**Comment by kingwill101** [comment]
> @kingwill101 thanks for your response. So for this usecase it would be better to create a custom module that parses the json string into e.g. `$100` right?

that's one approach or you could do something like

```dart

FilterRegistry.register('money', (input, args, namedArgs) {

    Currency currency = Currency.create( namedArgs['currency'] ?? 'USD', 2);

    // Create money from an int.
    Money costPrice = Money.fromIntWithCurrency(input, currency);
    return costPrice.toString()

});
```

```liquid
{{ 100 | money: currency: USD }}
```

haven't tested but this is using the example from the https://pub.dev/packages/money2 package to handle the currency

**Comment by cka29** [comment]
Thank you for the hint! Will post a working example if I have one anytime soon!
