### ISSUE TITLE
Variable names containing dash throws error

### ISSUE THREAD

**Issue by cka29** [kingwill101/liquify#3]
This template 
```
<p> {{ person.first-name }} </p>
```

with following data 
```
{
	"person": {
		"first-name": "John"
	}
}
```

does not render and logs this issue `parseInput: end of input expected @ 1:9`. But when using `first_name` (underscore instead dash) in data and template it works. Is there any restriction here? https://pub.dev/packages/liquid_engine had no issues with dash separators in variable names or in template. 🙏

**Comment by cka29** [comment]
I have forked the package and added dash support! 😊 Please ping me if this feature would be relevant for your package too

**Comment by kingwill101** [comment]
@cka29 can you create a pr with the changes?
