### ISSUE TITLE
Whitespace control

### ISSUE THREAD

**Issue by cka29** [kingwill101/liquify#8]
Would be nice if whitespace control is supported. 

https://shopify.github.io/liquid/basics/whitespace/

Or is there anything that avoids new lines in the rendered template for liquid code?

**Comment by cka29** [comment]
Here is the PR to handle whitespace control characters from the `liquid_engine` package https://github.com/ergonlabs/liquid_dart/pull/12/files#diff-3d7e904a479616d32ab0caeb8efe4eb3388b08a858792927ee3356d3b1985709 if this helps

**Comment by kingwill101** [comment]
sorry for the delay, this is partially resolved in #9 
Will need to spend some more time working on a better solution
